[package]
name = "detaxine-ui-cli"
version = "0.8.62"
edition = "2024"
description = "The Official CLI for Detaxine UI"
license = "MIT OR Apache-2.0"
license-file = "../../LICENSE-APACHE"
repository = "https://github.com/detaxine-rs/detaxine-ui"
homepage = "https://detaxine-rs.github.io/detaxine-ui/"
documentation = "https://docs.rs/detaxine-ui"
readme = "../../README.md"
keywords = ["leptos", "ui", "wasm", "rust", "components"]
categories = ["web-programming", "command-line-utilities"]

[[bin]]
name = "dtx"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
inquire = { workspace = true }
reqwest = { workspace = true }
indicatif = { workspace = true }
colored = { workspace = true }
anyhow = { workspace = true }
regex = { workspace = true }
toml_edit = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }


[package.metadata.docs.rs]
no-deps = true
