[package]
name = "detaxine-ui"
version = "0.8.60"
edition = "2024"
description = "A UI Library for Leptos"
license = "MIT OR Apache-2.0"
license-file = "../../LICENSE-APACHE"
repository = "https://github.com/detaxine-rs/detaxine-ui"
homepage = "https://detaxine-rs.github.io/detaxine-ui/"
documentation = "https://docs.rs/detaxine-ui"
readme = "../../README.md"
keywords = ["leptos", "ui", "wasm", "rust", "components"]
categories = ["web-programming", "wasm"]

[dependencies]
leptos = { workspace = true }
web-sys = { workspace = true }
gloo = { workspace = true }
js-sys = { workspace = true }
markdown = { workspace = true }
chrono = { workspace = true }
icondata = { workspace = true }
leptos_icons = { workspace = true }
leptos_meta = { workspace = true }
wasm-bindgen-futures = { workspace = true }
gloo-file = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
leptos_router = { workspace = true }
tailwind_fuse = "0.3.2"

[features]
default = ["csr"]
csr = ["leptos/csr"]
ssr = ["leptos/ssr"]
hydrate = ["leptos/hydrate"]

[dev-dependencies]
wasm-bindgen-test = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
leptos_axum = "0.8.10"
axum = "0.8.9"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "net", "macros"] }
any_spawner = { version = "0.3", features = ["tokio"] }
tower-http = { version = "0.7.0", features = ["fs"] }

[package.metadata.leptos]
output-name = "ssr_check"
site-root = "target/site"
site-pkg-dir = "pkg"
site-addr = "127.0.0.1:3000"
env = "DEV"

[package.metadata.docs.rs]
no-deps = true
